### ISSUE TITLE
Allow selection of table content

### ISSUE THREAD

**Issue by thepill** [MicroDroid/vue-materialize-datatable#13]
## Current behaviour:

Selecting text of a row leads to call the `click` method and firing of the `row-click` event.

## Idea:

Allow selecting of text from a row without firing the `row-click` event. This could be done by checking the value of  `getSelection()` by the browser api. Also this could be configurable by a prop like `allow-selection`.

**Comment by MicroDroid** [comment]
It doesn't need to have a `allow-selection` prop, as this is an incorrect behavior entirely.

This should be fixed as you purposed
