### ISSUE TITLE
Wrong data taken in table

### ISSUE THREAD

**Issue by DaniloPolani** [MicroDroid/vue-materialize-datatable#15]
The table is getting wrong field from columns specs. Furthermore, `perPage` is not working. Table:

```
<datatable
        v-if="type == 'collapsed'"
        :columns="collapsed_columns"
        :rows="$parent.lines"
        :perPage="50"></datatable>
```
This is my columns array:

```
collapsed_columns: [
          {
            label: 'Method',
            field: 'method',
            html: true,
            width: '100px'
          },
          {
            label: 'URL',
            field: 'url',
            width: '30%'
          }
        ]
```

Rows: 

```
[
  {
    date:"21/Jun/2017 06:36:18"
    last_agent:"\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36\""
    method:"<span class=\"tag is-info\">GET</span>"
    url:"/favicon.ico?_=517989746"
  }
]
```

And this is the (wrong) result. I'm using it with Single App Component inside Electron.

![Example screenshot](https://user-images.githubusercontent.com/6277291/27510621-1f28e364-5915-11e7-8035-b5f92c6d1a04.png)

**Comment by thepill** [comment]
@DaniloPolani The data is displayed correctly for me. 

<img width="1249" alt="bildschirmfoto 2017-06-24 um 21 49 24" src="https://user-images.githubusercontent.com/8901210/27511538-0c14fce2-5927-11e7-9b95-b9d0d0091744.png">


In your data example you are missing the `,` after each property within your row element - could you try fixing this? my node server will throw an error if i leave them, so i can not test it at the moment.

**Comment by DaniloPolani** [comment]
The missing comma is because it was the "dump" from Vue devtools, anyway in your screenshot the URL is in place of method...

**Comment by thepill** [comment]
*facepalm* will investigate this...

**Comment by thepill** [comment]
@DaniloPolani fixed in the next npm release.

<img width="1365" alt="bildschirmfoto 2017-06-25 um 13 19 16" src="https://user-images.githubusercontent.com/8901210/27515667-f4edbab8-59a8-11e7-8089-12fefde86dbf.png">


@MicroDroid Could you please update the npm package, thanks.

**Comment by DaniloPolani** [comment]
Thank you, I'm waiting for the updated npm version :)

**Comment by MicroDroid** [comment]
Updated.
