### ISSUE TITLE
Property [perPage] not working

### ISSUE THREAD

**Issue by thepill** [MicroDroid/vue-materialize-datatable#16]
As mentioned in #15 setting the `perPage ` property is not working.

**Comment by thepill** [comment]
@MicroDroid Would like to rewrite this (eg. using v-model to bind the per page selection). Any concerns?

**Comment by MicroDroid** [comment]
@thepill Can I see a reproduction of this on a JSFiddle or something? I couldn't reproduce it myself.

Other than that, I am okay with a rewrite to the internals of that as long as the API stays the same, and well, doesn't add too much complexity
