### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by MicroDroid** [MicroDroid/vue-materialize-datatable#20]
The documentation is so much larger than just fitting in a code block. The documentation should be split somehow or converted to a Markdown table.

**Comment by rodrigoAbril** [comment]
sorry noob question... does this work with vue2?

**Comment by thepill** [comment]
@rodrigoAbril yes it does

**Comment by MicroDroid** [comment]
44ec95bb61a309cad2a9f23ef8ca1fb9eaef05f9 addresses the question above

**Comment by DMeechan** [comment]
Could you add the source code for the table shown in the README screenshot to the documentation? Would be handy to know how to do the delete action buttons.

**Comment by MicroDroid** [comment]
@DMeechan Added in 023c900
