### ISSUE TITLE
Allow localisation (L10N) of this component

### ISSUE THREAD

**Issue by yar0d** [MicroDroid/vue-materialize-datatable#25]
Hello,
It would be great if we could modify the text that are displayed so that we can translate it. By text, I mean text displayed by the table, like « Rows per page ».

Thanks

**Comment by MicroDroid** [comment]
This is definitely a good improvement, however, I have currently no time to implement this myself

**Comment by MicroDroid** [comment]
This has been implemented. See [here](https://github.com/MicroDroid/vue-materialize-datatable/#localization) for usage.
