### ISSUE TITLE
"TypeError: computedRows.sort is not a function" how to fix this error?

### ISSUE THREAD

**Issue by jeanmari** [MicroDroid/vue-materialize-datatable#27]
this is the component 

`<datatable v-if="rows" v-on:row-click="onRowClick" title="List of Rooms" :columns="columns" :rows="rows" :perPage="[10, 20, 30, 40, 50]"></datatable>`

and the ajax

`axios.get('api/rows')
					.then(function(response){
						vm.rows= response.data;
						console.log(vm.rows)
					});`

**Comment by MicroDroid** [comment]
It looks like you have been having problems with passing data the component, and by closing this issue it looks like it has been resolved for you.

If anybody gets similar error, I would need to see the data you're passing to the component.
