### ISSUE TITLE
Documentation of materialize.css and Google Material Icons requirements

### ISSUE THREAD

**Issue by thepill** [MicroDroid/vue-materialize-datatable#3]
## Currently
The documentation does not provide some information that `materialize.css` and `Google Material Icons Font` are needed (especially the google font for the used icons).
The readme should be updated.

## Expected
The readme should guide you to import the required css styles and web fonts

**Comment by MicroDroid** [comment]
@thepill Done. as per 60ab38266014167623612e5d5c9b27cca8c5263b

**Comment by thepill** [comment]
Would also like to contribute more - are there any open plans/todos you have?

**Comment by MicroDroid** [comment]
@thepill Well there's implementing checked datatables, I tried that once but I couldn't style it properly with CSS

![image](https://cloud.githubusercontent.com/assets/8523135/25727220/b03b2bb2-3130-11e7-9793-8cf8d22b2628.png)

The table should look something like this when items are checked:

![image](https://cloud.githubusercontent.com/assets/8523135/25727215/a9731394-3130-11e7-8299-f0438652df8c.png)

And the buttons above should probably be also customizable.
