### ISSUE TITLE
How i can hide table column?

### ISSUE THREAD

**Issue by IhorVimmi** [MicroDroid/vue-materialize-datatable#31]

**Comment by thepill** [comment]
@IhorVimmi Please provide more information. What are you trying to do?

**Comment by IhorVimmi** [comment]
I have next code
`<datatable title="Candidates" :rows="status.items" :columns="tableHead" :customButtons="customButtons" ></datatable>`
`status.items` and `tableHead` include information about people
Also i add custom button for open table settings modal
In modal i have checkboxes for each `tableHead` item
When i change any checkbox i need hide same column in table. How i can do this? 
For buttons you have `hide` boolean option but do you have somethink same for columns? 
For example:
http://joxi.ru/8Anx94dhjLYX5m - My table
http://joxi.ru/MAj39vQs4enwor - modal with table settings 
Thanks!

**Comment by thepill** [comment]
You have to update your 'tableHead' array wich will reactivley will update your table.

**Comment by IhorVimmi** [comment]
oh thanks!!
