### ISSUE TITLE
Duplicate keys detected: '0'. This may cause an update error

### ISSUE THREAD

**Issue by marteoma** [MicroDroid/vue-materialize-datatable#35]
![image](https://user-images.githubusercontent.com/18709765/45458877-5e2dce80-b6bb-11e8-81ba-7697fb4813f3.png)

That is my component, it render well, but sometimes doesn't load, and I get these errors repeatly:
![image](https://user-images.githubusercontent.com/18709765/45458912-8ddcd680-b6bb-11e8-950f-02106e7277d5.png)
What must be done to fix that.

**Comment by MicroDroid** [comment]
This has to do with the data you're providing. You do have duplicate keys in your data or it doesn't work with datatable in some way. Please send a `console.log` of `columns` and `data` in order to help you any further.

**Comment by marteoma** [comment]
![image](https://user-images.githubusercontent.com/18709765/45580011-e34aec00-b851-11e8-9a41-073bb3c90f79.png)
 
These are the two props

**Comment by MicroDroid** [comment]
@marteoma `data` must be an array of objects, not an object itself.

**Comment by marteoma** [comment]
Sorry, but that's not the mistake, I was passing an array, just forgot to use it this time.

**Comment by ermand** [comment]
@MicroDroid I am having the same error for the following `columns` and `data`

![image](https://user-images.githubusercontent.com/2822729/48984410-885c2d80-f0fb-11e8-85d1-b99340014db3.png)

**Comment by ermand** [comment]
@MicroDroid please check my repo: https://github.com/ermand/vue-materialize-datatable-testing

Thanks in advance :)

**Comment by MicroDroid** [comment]
Thanks a lot for creating the repository, I will check it out as soon as
possible and get back to you

**Comment by adi-darachi** [comment]
Is this going to be merged?
