### ISSUE TITLE
Table css is lost when printing

### ISSUE THREAD

**Issue by Matt-NGP** [MicroDroid/vue-materialize-datatable#40]
Hi,

I'm interested in using the data table. The only issue is that the table css is missing on print. Is it possible to include the table CSS on print?

Thanks,
Matt

**Comment by MicroDroid** [comment]
It would be interesting to get experiment with that. I put this on my todo and will have a look when I have time to. Feel free to experiment yourself too meanwhile since the code is very easy and straightforward

**Comment by MicroDroid** [comment]
There's a tiny tiny little overflow bug issue while rendering table on only Chrome, but so far the feature can be considered as implemented. It'll be available in the next release.
