### ISSUE TITLE
Error in render: "RangeError: invalid array length

### ISSUE THREAD

**Issue by OscarCPweb** [MicroDroid/vue-materialize-datatable#46]
The last update i found one error
when i want to show all datas in the datatable, it throw this error
`Error in render: "RangeError: invalid array length`

How to solve it? thanks

**Comment by OscarCPweb** [comment]
Hello, u will work on this or not?

**Comment by MicroDroid** [comment]
Provide code so I can check what's wrong. Provide data as well.

**Comment by OscarCPweb** [comment]
[Datatables.vue.zip](https://github.com/MicroDroid/vue-materialize-datatable/files/3873130/Datatables.vue.zip)

When i put show all datas (10, 20, 50, all) return this error E`rror in render: "RangeError: invalid array length
`
Im doing **serversearch** if this can help you.

Thanks

**Comment by MicroDroid** [comment]
You're supposed to send me the code for how you use the datatable, not the library itself.

Closing due to unclear bug report.
