### ISSUE TITLE
Any template with this datatables?

### ISSUE THREAD

**Issue by herickwilke** [MicroDroid/vue-materialize-datatable#49]
Hi.

I tryed to install the table in my project several times and always getting some errors, in a point that I destroyed my entire project. 

I wonder if have some theme that already have the datatable that I can download and modify the project to use? If not, can someone create a empty vue project and install the tables and send it to me, please?

Sorry, I'm new to vue, i'm trying.. and i really need this datatables.

Thanks!

**Comment by MicroDroid** [comment]
This is a plugin not a framework. Read the docs in detail.
