### ISSUE TITLE
Spacing between table cells on IE11

### ISSUE THREAD

**Issue by thepill** [MicroDroid/vue-materialize-datatable#5]
`border-radius`  of `materialize.css`  leads to small visible spaces between table cells on IE11:
![capture](https://cloud.githubusercontent.com/assets/8901210/26403735/96c657c4-408f-11e7-9da4-830239b2e40f.PNG)

Possible fix:

```
table td, table th {
    border-radius: 0;
}
```

**Comment by MicroDroid** [comment]
I do not have any device that has Windows so that I am able to reproduce or fix that. If that seems like a proper fix please pull-request that.

**Comment by thepill** [comment]
`border: none` removes the whole border and therfore the table isn't stripped anymore. The 1-pixel vertical line is also gone if you set `border-radius` to `0`

**Comment by MicroDroid** [comment]
Fixed as in #6
