### ISSUE TITLE
Invalid prop: type check failed for prop "customButtons". Expected Function, got Array 

### ISSUE THREAD

**Issue by fancar** [MicroDroid/vue-materialize-datatable#52]
Hello. 
I faced with this warning if I pass custom buttons this way:
                {
                    hide:false,
                    icon:"settings",
                    onclick: function () {
                        console.log('btn pressed')
                    }
                }
I got prop warning "Expected Function, got Array "

As far as know in vuejs-way to pass some state from child to parent is emit\v-on. How can I pass some emit from these custom buttons via the 'onclick' function in buttons array?

Thank you.

**Comment by MicroDroid** [comment]
Please provide more code, preferably in a codesandbox.
