### ISSUE TITLE
Exported Excel has HTML tags

### ISSUE THREAD

**Issue by D-sense** [MicroDroid/vue-materialize-datatable#54]
Hi,

Thanks for this amazing package.

I am facing an issue. Each time I export the data in Excel, the generated Excel comes with HTML tags, as pasted below. 

```
<table><thead><tr><th>Character | name</th><th>First | appearance</th><th>Created | by</th><th>Voiced | by</th></tr></thead><tbody><tr><td>Abu</td><td>Alladin | (1992)</td><td>Joe | Grant</td><td>Frank | Welker</td></tr><tr><td>Magic | Carpet</td><td>Alladin | (1992)</td><td>Randy | Cartwright</td><td>N/A</td></tr><tr><td>The | Sultan</td><td>Alladin | (1992)</td><td>Navid | Negahban</td><td>Douglas | Seale</td></tr></tbody></table>
```

Please is there a fix to this?
Thanks

**Comment by MicroDroid** [comment]
As in, the HTML tags get inserted into the Excel document itself?

Excel is generated by outputting some HTML in a format old Excel versions understand. I can't tell whether you use some Excel without backwards compatibility or what.

Screenshots preferred.

**Comment by D-sense** [comment]
Thanks for your reply @MicroDroid. It seems the markdown does not get parsed correctly on Mac. It works as expected on Windows.

**Comment by MicroDroid** [comment]
Huh what Markdown though, an issue on a platform is still a bug
