### ISSUE TITLE
Using bootstrap

### ISSUE THREAD

**Issue by khayyak** [MicroDroid/vue-materialize-datatable#57]
hello , I want to ask about using bootstrap classes with datatable . is it possible or not ? because I want to change table style .

Thanks in advance

**Comment by MicroDroid** [comment]
This datatable strictly follows Material Design's spec - so customizing its style is against its principle itself.

Let me know if this answers your question.

**Comment by khayyak** [comment]
thanks for reply , but I want to know how can I change datatable style , I mean changing thead and tbody ... styles .

**Comment by MicroDroid** [comment]
You cannot.

**Comment by khayyak** [comment]
thanks for your reply .
