### ISSUE TITLE
Change table current page

### ISSUE THREAD

**Issue by msantelices** [MicroDroid/vue-materialize-datatable#58]
Is there a method to programatically change the current page of the table? Specifically, implement something like a button and when you click it, your table automatically goes to page 1?

**Comment by MicroDroid** [comment]
If I recall correctly there isn't, you could though PR an API for that or something.

**Comment by MicroDroid** [comment]
Actually just checked, maybe you'd be able to call `nextPage()` directly on the ref, maybe try that?
