### ISSUE TITLE
Pagination, right and left arrows get darker and darker when you click them until you can't see the icons

### ISSUE THREAD

**Issue by dwhudson** [MicroDroid/vue-materialize-datatable#62]
![darker](https://user-images.githubusercontent.com/8238577/94584663-2b23ec80-023c-11eb-82bb-a04d1e874a19.PNG)
![arrows_darker](https://user-images.githubusercontent.com/8238577/94583578-daf85a80-023a-11eb-913e-67b0311e2e9a.PNG)

I've seen this on the demo page as well as my own local datatable. When you click on the pagination buttons for left or right. The buttons get darker until the point where you cant see the icons. Any have a thought/potential fix for this? 

I'm thinking short term to track down the css and disable/simplify the click,hover effects. 

***** Looks like this issue can be closed. Problem is caused by materialize being imported multiple times on a page. This is a materialize css issue. I found a few cases of multiple imports I had throughout my app. ******

**Comment by MicroDroid** [comment]
Indeed I had just checked, this does not occur on my local build. It's most likely a materialize css issue.
