### ISSUE TITLE
Exporting options for Cyrillic?

### ISSUE THREAD

**Issue by WhatNot911** [MicroDroid/vue-materialize-datatable#66]
![image](https://user-images.githubusercontent.com/22567537/101478481-cedaf880-3961-11eb-9581-cd1fac114818.png)
This is what I get instead of Cyrillic. Appears to be encoding error or something. Are there any export settings beyond "exportable" ? Or is it not even VMD issue?

**Comment by MicroDroid** [comment]
Most likely font issues on your end, not sure though

**Comment by WhatNot911** [comment]
Maybe. But I figured a way to "hackfix" i I guess.
This requires editing DataTable.vue file's method **exportExcel()**;

original piece of code on line 321:
`const html = this.renderTable().replace(/ /g, '%20');`
changing this to
`const html = ('<head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta LANG="ru"><meta charset="utf-8"></head>' + this.renderTable()).replace(/ /g, '%20');`
causes all xls files to display proper cyrillic (or at least Russian) words.
I don't know how useful this is but I decided to leave this here anyways.

**Comment by MicroDroid** [comment]
Ah you didn't even mention that this was in the spreadsheet export and not the table.

Then yes, well hm, can you open a PR?

**Comment by WhatNot911** [comment]
Oh sorry, I didn't know there were more than one way to export the table.
Anyway I'm not that savvy to know how to open an RP or what it really is, or how to do it properly. I mean hardcoding in meta tags doesn't seem to be a right solution for this "lesser issue". I'd rather close this Untill I figure out how to do this properly (or when someone else does this the right way), I'm not putting my low programming skills in this package, what if I break something?
Anyways thanks for the feedback.
