### ISSUE TITLE
Dispatch event on click containing the row object

### ISSUE THREAD

**Issue by thepill** [MicroDroid/vue-materialize-datatable#9]
## Proposal
If you click on a row a `vue custom event` will be emitted, containing the object in the `payload`.

You would be able to react to the click event in the parent element via `v-on:customEvent`.

## Discussion

Would you be interested in this feature? I would see this as a replacement for the `onClick` function thing. I have implemented this in my own project.

**Comment by MicroDroid** [comment]
I did not know the possibility of defining custom events and would rather probably used that instead of `onClick` if I knew about it. Feel free to make a pull request about that or I might implement it myself later.

Good one 👌

**Comment by thepill** [comment]
Do you have a basic `demo`setup for running this in `dev`?

**Comment by MicroDroid** [comment]
@thepill Demo setup? You mean an example of using `onClick`?

**Comment by thepill** [comment]
the whole component. How do you test your changes? Is there another way to communicate directly to you, like messaging or something?

**Comment by MicroDroid** [comment]
@thepill Check your email inbox :+1:
